name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker Image
      run: docker build -t phallenyeng168/cicdhtmlimage:latest .

    - name: Publish Image to Docker Hub
      run: docker push phallenyeng168/cicdhtmlimage:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Docker Image
        run: docker pull phallenyeng168/cicdhtmlimage:latest

      - name: Delete Old Container
        run: docker rm -f htmlContainer

      - name: Run Docker Container
        run: docker run -d -p 5000:80 --name htmlContainer phallenyeng168/cicdhtmlimage
      
